[tool.poetry]
name = "update_vim_plugins"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "update_vim_plugins"}]

[tool.poetry.scripts]
update-vim-plugins = "update_vim_plugins.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
cleo = "^2.0.1"
jsonpickle = "*"
dateparser = "1.1.8"
PyYAML = "^6.0"

[tool.poetry.group.test.dependencies]
pytest-cov = "^4.0.0"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# black = "^23.3.0"
# ruff-lsp = "^0.0.24"
# mypy = "^1.2.0"
# types-requests = "^2.28.11.17"
# isort = "^5.12.0"
# ruff = "^0.0.262"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
