[tool.poetry]
name = "update_vim_plugins"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "update_vim_plugins"}]

[tool.poetry.scripts]
update-vim-plugins = "update_vim_plugins.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
cleo = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.0.0"
pytest = "^7.3.1"
black = "^23.3.0"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
