name: Remove blacklisted entries from manifest.txt

runs:
  using: 'composite'
  steps:
    - name: Cleanup manifest
      shell: bash
      run: |
        sort -o ./manifest.txt ./manifest.txt
        sort -o ./blacklist.txt ./blacklist.txt
        # remove all files that are in my blacklist
        echo "$(comm -23 ./manifest.txt ./blacklist.txt)" > ./manifest.txt
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ github.token }}
    - name: Backup vim-plugins.nix # TODO: workaround: if vim-plugins is broken, all 'nix run' actions will fail
      shell: bash
      run: |
        mv ./pkgs/vim-plugins.nix ./pkgs/vim-plugins.nix.bak
        echo "{ ...} : {}" > ./pkgs/vim-plugins.nix
    - name: Generate derivations for new plugins
      shell: bash
      run: |
        nix run .#update-vim-plugins -- cleanup ./manifest.txt
    - name: Restore vim-plugins.nix
      shell: bash
      run: |
        mv ./pkgs/vim-plugins.nix.bak ./pkgs/vim-plugins.nix
